---

# Vector Operations and Dot Product

The __weighted sum__ of two vectors is also known as the __dot product__. It is composed from an  __elementwise_multiplication__ operation followed by a __vector_sum__ operation.

In [12]:
def elementwise_multiplication(vec_a, vec_b):
    assert(len(vec_a) == len(vec_b))
    result = []
    for idx in range(len(vec_a)):
        result.append(vec_a[idx] * vec_b[idx])
    return result
    
def vector_sum(vec_a):
    result = 0
    for a in vec_a:
        result += a
    return result

def dot_product(vec_a, vec_b):
    return vector_sum(elementwise_multiplication(vec_a, vec_b))

def weighted_sum(inputs, weights):
    assert(len(inputs) == len(weights))
    prediction = 0
    for idx in range(len(weights)):
        prediction += inputs[idx] * weights[idx]
    return prediction

In [13]:
vec_a = [1, 2, 3]
vec_b = [4, 5, 6]

ewm = elementwise_multiplication(vec_a, vec_b)
print("elementwise_multiplication {} {}   = {}".format(vec_a, vec_b, ewm))
                     
vs = vector_sum(ewm)
print("vector_sum                           {} = {}".format(ewm, vs))

print("--------------------------------------------------------------")

dp = dot_product(vec_a, vec_b)
print("=> dot_product             {} {}   = {}".format(vec_a, vec_b, dp))

ws = weighted_sum(vec_a, vec_b)
print("=> weighted_sum            {} {}   = {}".format(vec_a, vec_b, ws))

elementwise_multiplication [1, 2, 3] [4, 5, 6]   = [4, 10, 18]
vector_sum                           [4, 10, 18] = 32
--------------------------------------------------------------
=> dot_product             [1, 2, 3] [4, 5, 6]   = 32
=> weighted_sum            [1, 2, 3] [4, 5, 6]   = 32


---

# Dot Product - Logical Intutition

A dot product gives us a _notion of similarity_ between two vectors. 

Rougly speaking, __a neuron gives a high score to an input based on how similar it is to the neuron weights__. If inputs align with weights then they will increase the magnitude of the dot product. If both input and weight have a negative cardinality then they still produce a positive contribution to the final dot product.

In [16]:
i1 = [ 0, 1, 0, 1]
w1 = [ 0, 1, 0, 1]
w2 = [ 1, 0, 1, 0]

print("dot_product i1: {}".format(i1))
print("            w1: {}".format(w1))
print("            =   {}".format(dot_product(i1, w1)))      
print("")
print("dot_product i1: {}".format(i1))
print("            w2: {}".format(w2))
print("            =   {}".format(dot_product(i1, w2)))      
print("")

dot_product i1: [0, 1, 0, 1]
            w1: [0, 1, 0, 1]
            =   2

dot_product i1: [0, 1, 0, 1]
            w2: [1, 0, 1, 0]
            =   0



Rougly speaking, with regard to the dot product, the weights in a network can be read with a logical interpretation. The 'elementwise_multiplication' operation is similar to a __logical and__ operation; the 'vector_sum' operation is similar to a __logical or__ operation, and, negative weights (without aligning negative inputs) are similar to a __logical not__ operation. However, the cardinality of the weights and the input also have an effect on the resulting dot product. For example:

__[ 1  , 0, 1  ]__ => if input[0] OR input[2]

__[ 0  , 0, 1  ]__ => if input[2]

__[ 1  , 0, -1 ]__ => if input[0] OR NOT input[2] 

__[ -1 , 0, -1 ]__ => if NOT input[0] OR NOT input[2] 

__[ 0.5, 0, 1  ]__ => if BIG input[0] or input[2]

---

# Numpy Linear Algebra

In [30]:
import numpy as np
a = np.array([0,1,2,3]) # a vector
b = np.array([4,5,6,7]) # another vector 
c = np.array([a, b])    # a matrix
d = np.zeros((2,4))     #(2x4 matrix of zeros) 
e = np.random.rand(2,5) # random 2x5

print("\x1b[1;31mvector a\x1b[0m\n{}".format(a))
print("\x1b[1;31mvector b\x1b[0m\n{}".format(b))
print("\x1b[1;31mmatrix c\x1b[0m\n{}".format(c))
print("\x1b[1;31mmatrix d\x1b[0m\n{}".format(d))
print("\x1b[1;31mmatrix e\x1b[0m\n{}".format(e))

print("\x1b[1;31ma * 0.1\x1b[0m\n{}".format(a * 0.1))
print("\x1b[1;31mc * 0.2\x1b[0m\n{}".format(c * 0.2))
print("\x1b[1;31ma * b\x1b[0m\n{}".format(a * b))
print("\x1b[1;31ma * b * 0.2\x1b[0m\n{}".format(a * b * 0.2))
print("\x1b[1;31ma * c\x1b[0m\n{}".format(a * c))


vector a
[0 1 2 3]
vector b
[4 5 6 7]
matrix c
[[0 1 2 3]
 [4 5 6 7]]
matrix d
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
matrix e
[[ 0.55186598  0.71069333  0.56309558  0.81975941  0.68318827]
 [ 0.71118332  0.23710668  0.5412132   0.76864242  0.31892795]]
a * 0.1
[ 0.   0.1  0.2  0.3]
c * 0.2
[[ 0.   0.2  0.4  0.6]
 [ 0.8  1.   1.2  1.4]]
a * b
[ 0  5 12 21]
a * b * 0.2
[ 0.   1.   2.4  4.2]
a * c
[[ 0  1  4  9]
 [ 0  5 12 21]]
